#!/usr/bin/env bash
# switch-kenl.sh
# Switch between KENL contexts with visual themes
# Compatible with rpm-ostree immutable systems (user-space only)

set -euo pipefail

FACADES_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROMPTS_DIR="$FACADES_DIR/prompts"
CONFIG_DIR="$HOME/.config/kenl-facades"

# Create config directory if it doesn't exist
mkdir -p "$CONFIG_DIR"

# Function to display available contexts
show_contexts() {
    echo "Available KENL contexts:"
    echo ""
    echo "  0) KENL0-system     ⚙️  White   - System Operations (Elevated)"
    echo "  1) KENL1-framework  ⚛️  Purple  - ATOM+SAGE+OWI Core"
    echo "  2) KENL2-gaming     🎮  Red     - Bazzite Gaming (GWI)"
    echo "  3) KENL3-dev        💻  Blue    - Bazzite-DX Development"
    echo "  4) KENL4-monitoring 📊  Green   - Monitoring & Observability"
    echo "  5) KENL5-facades    🎨  Yellow  - Facades & Theming"
    echo ""
}

# Function to activate a KENL context
activate_context() {
    local context="$1"
    local prompt_file="$PROMPTS_DIR/kenl${context}.sh"

    if [ ! -f "$prompt_file" ]; then
        echo "Error: Prompt file not found: $prompt_file"
        exit 1
    fi

    # Save current context
    echo "$context" > "$CONFIG_DIR/current-context"

    # Create/update .kenl_profile in user home
    cat > "$HOME/.kenl_profile" <<EOF
# KENL Context Configuration
# Auto-generated by switch-kenl.sh
# Source this in your .bashrc or .bash_profile

# Load KENL context prompt
if [ -f "$prompt_file" ]; then
    source "$prompt_file"
fi

# KENL-specific environment
export KENL_ROOT="$HOME/kenl"
export KENL_FACADES="$FACADES_DIR"
export PATH="\$KENL_ROOT/KENL1-framework/atom-sage-framework:\$PATH"
EOF

    echo "✅ Activated KENL$context context"
    echo ""
    echo "Add this to your ~/.bashrc to persist:"
    echo ""
    echo "    # KENL Context"
    echo "    [ -f ~/.kenl_profile ] && source ~/.kenl_profile"
    echo ""
    echo "Then restart your shell or run: source ~/.bashrc"
}

# Function to install systemwide (rpm-ostree compatible)
install_systemwide() {
    echo "Installing KENL facades systemwide (rpm-ostree compatible)..."
    echo ""

    # Check if running on immutable system
    if command -v rpm-ostree &> /dev/null; then
        echo "✅ Detected rpm-ostree system (Bazzite)"
        echo ""
        echo "Installing in user space (respects immutability):"
        echo "  - Themes: ~/.config/kenl-facades/"
        echo "  - Prompts: ~/.kenl_profile"
        echo "  - No system modifications required"
    fi

    # Create profile hook
    if ! grep -q "kenl_profile" "$HOME/.bashrc" 2>/dev/null; then
        echo "" >> "$HOME/.bashrc"
        echo "# KENL Facades Integration" >> "$HOME/.bashrc"
        echo "[ -f ~/.kenl_profile ] && source ~/.kenl_profile" >> "$HOME/.bashrc"
        echo "✅ Added KENL integration to ~/.bashrc"
    else
        echo "✅ KENL integration already in ~/.bashrc"
    fi

    # Set default context if none exists
    if [ ! -f "$CONFIG_DIR/current-context" ]; then
        echo "1-framework" > "$CONFIG_DIR/current-context"
        activate_context "1-framework"
    fi

    echo ""
    echo "✅ Installation complete!"
    echo ""
    echo "Restart your shell or run: source ~/.bashrc"
}

# Function to show current context
show_current() {
    if [ -f "$CONFIG_DIR/current-context" ]; then
        local context=$(cat "$CONFIG_DIR/current-context")
        echo "Current context: KENL$context"
    else
        echo "No context active. Run 'switch-kenl.sh install' to set up."
    fi
}

# Main command handler
case "${1:-}" in
    0|kenl0|system)
        activate_context "0-system"
        ;;
    1|kenl1|framework)
        activate_context "1-framework"
        ;;
    2|kenl2|gaming)
        activate_context "2-gaming"
        ;;
    3|kenl3|dev|development)
        activate_context "3-dev"
        ;;
    4|kenl4|monitoring)
        activate_context "4-monitoring"
        ;;
    5|kenl5|facades)
        activate_context "5-facades"
        ;;
    install)
        install_systemwide
        ;;
    current|status)
        show_current
        ;;
    list|help|--help|-h)
        show_contexts
        echo "Usage: $0 [context|install|current|list]"
        echo ""
        echo "Examples:"
        echo "  $0 1           # Switch to KENL1 (framework)"
        echo "  $0 gaming      # Switch to KENL2 (gaming)"
        echo "  $0 install     # Install systemwide"
        echo "  $0 current     # Show current context"
        ;;
    *)
        echo "Error: Unknown context '$1'"
        echo ""
        show_contexts
        echo "Run '$0 help' for usage"
        exit 1
        ;;
esac
