# 05-Configure.ps1
# Final configuration phase
# Version: 1.0.0

$scriptRoot = Split-Path $PSScriptRoot -Parent
Import-Module "$scriptRoot\core\Display.psd1" -Force -Global
Import-Module "$scriptRoot\core\Logger.psd1" -Force -Global

function Invoke-FinalConfiguration {
    param(
        [Parameter(Mandatory=$true)]
        [hashtable]$Config
    )

    Write-Section -Title "Final Configuration" -Icon "⚙️"
    Write-Log -Message "Starting final configuration" -Level "INFO"

    try {
        # Update server.properties
        Write-StatusBox -Title "Configuring server.properties" -Status "Processing" -Type "Progress"

        $serverPropsPath = Join-Path $Config.ServerPath "server.properties"
        if (Test-Path $serverPropsPath) {
            $props = Get-Content $serverPropsPath

            # Update settings
            $props = $props -replace "server-port=.*", "server-port=$($Config.ServerPort)"
            $props = $props -replace "max-players=.*", "max-players=$($Config.MaxPlayers)"
            $props = $props -replace "view-distance=.*", "view-distance=$($Config.ViewDistance)"
            $props = $props -replace "simulation-distance=.*", "simulation-distance=$($Config.SimulationDistance)"
            $props = $props -replace "gamemode=.*", "gamemode=$($Config.Gamemode)"
            $props = $props -replace "difficulty=.*", "difficulty=$($Config.Difficulty)"
            $props = $props -replace "online-mode=.*", "online-mode=$($Config.OnlineMode.ToString().ToLower())"
            $props = $props -replace "pvp=.*", "pvp=$($Config.PVP.ToString().ToLower())"
            $props = $props -replace "motd=.*", "motd=ClaudeNPC Server - AI Powered NPCs"

            $props | Set-Content $serverPropsPath
            Write-StatusBox -Title "server.properties" -Status "Updated" -Type "Success"
        }

        # Create ClaudeNPC config if API key provided
        if ($Config.ClaudeAPIKey -and $Config.ClaudeAPIKey -ne "") {
            Write-StatusBox -Title "Creating ClaudeNPC config" -Status "Processing" -Type "Progress"

            $pluginsPath = Join-Path $Config.ServerPath "plugins"
            $claudeConfigPath = Join-Path $pluginsPath "ClaudeNPC"

            if (-not (Test-Path $claudeConfigPath)) {
                New-Item -ItemType Directory -Path $claudeConfigPath -Force | Out-Null
            }

            $claudeConfig = @"
# ClaudeNPC Configuration
# Generated by ClaudeNPC Server Suite

# Anthropic API Configuration
api:
  # Your Anthropic API key
  key: "$($Config.ClaudeAPIKey)"

  # Model to use (claude-sonnet-4-20250514 recommended)
  model: "claude-sonnet-4-20250514"

  # Maximum tokens per response
  max_tokens: 300

  # Response creativity (0.0 to 1.0)
  temperature: 0.7

# Conversation Settings
conversation:
  # Number of messages to remember
  memory_length: 10

  # Minutes before conversation times out
  timeout_minutes: 5

  # Cooldown between interactions (seconds)
  cooldown_seconds: 3

# NPC Personalities
personalities:
  # Default personality for all NPCs
  default:
    system_prompt: |
      You are a helpful NPC in a Minecraft server. You are friendly,
      concise, and roleplay as a character in this world. Keep responses
      brief (1-2 sentences). You can give directions, share lore, or
      engage in light conversation.
"@

            $claudeConfig | Set-Content (Join-Path $claudeConfigPath "config.yml")
            Write-StatusBox -Title "ClaudeNPC config" -Status "Created" -Type "Success"
        } else {
            Write-StatusBox -Title "ClaudeNPC config" -Status "Skipped (no API key)" -Type "Warning"
        }

        # Display final settings
        Write-Host ""
        Write-Host "  Server Configuration:" -ForegroundColor Cyan
        Write-Host "  ───────────────────────────────────────" -ForegroundColor DarkCyan
        Write-Host "  Server Path:     $($Config.ServerPath)" -ForegroundColor Gray
        Write-Host "  Server Port:     $($Config.ServerPort)" -ForegroundColor Gray
        Write-Host "  Max Players:     $($Config.MaxPlayers)" -ForegroundColor Gray
        Write-Host "  Gamemode:        $($Config.Gamemode)" -ForegroundColor Gray
        Write-Host "  Difficulty:      $($Config.Difficulty)" -ForegroundColor Gray
        Write-Host "  Memory:          $($Config.MemoryMin) - $($Config.MemoryMax)" -ForegroundColor Gray
        Write-Host "  Install Profile: $($Config.InstallProfile)" -ForegroundColor Gray
        Write-Host "  ───────────────────────────────────────" -ForegroundColor DarkCyan
        Write-Host ""

        Write-StatusBox -Title "Final Configuration" -Status "Complete" -Type "Success"
        Write-Log -Message "Final configuration complete" -Level "SUCCESS"

        return @{
            Success = $true
            Message = "Configuration complete"
            Data = @{ServerPath = $Config.ServerPath}
        }

    } catch {
        Write-StatusBox -Title "Configuration Failed" -Status $_.Exception.Message -Type "Error"
        Write-LogError -ErrorRecord $_
        return @{Success = $false; Message = $_.Exception.Message; Data = @{}}
    }
}
