#!/usr/bin/env bash
#
# install-banner.sh - Install KENL banners to shell profiles
#
# Adds KENL banner to .bashrc, .zshrc, and terminal profiles
#

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BANNERS_DIR="$SCRIPT_DIR"

echo "🏠 KENL Banner Installation"
echo ""
echo "Choose banner style:"
echo "  1) Full (detailed ASCII art with all kennels)"
echo "  2) Kennels (multi-kennel layout with icons)"
echo "  3) Compact (smaller, terminal-friendly)"
echo "  4) Single (single kennel showcase)"
echo "  5) Minimal (tiny prompt banner)"
echo "  6) Context-aware (dynamic based on current KENL)"
echo "  7) None (remove banner)"
echo ""
read -rp "Choose [1-7]: " choice

# Determine banner command
case $choice in
    1)
        BANNER_CMD="cat \"$BANNERS_DIR/kenl-banner-full.txt\""
        ;;
    2)
        BANNER_CMD="cat \"$BANNERS_DIR/kenl-banner-kennels.txt\""
        ;;
    3)
        BANNER_CMD="cat \"$BANNERS_DIR/kenl-banner-compact.txt\""
        ;;
    4)
        BANNER_CMD="cat \"$BANNERS_DIR/kenl-banner-single.txt\""
        ;;
    5)
        BANNER_CMD="cat \"$BANNERS_DIR/kenl-banner-minimal.txt\""
        ;;
    6)
        BANNER_CMD="\"$BANNERS_DIR/kenl-banner-context.sh\""
        chmod +x "$BANNERS_DIR/kenl-banner-context.sh"
        ;;
    7)
        BANNER_CMD=""
        echo "Removing KENL banner..."
        ;;
    *)
        echo "❌ Invalid choice"
        exit 1
        ;;
esac

# Function to add banner to shell config
add_to_shell_config() {
    local config_file="$1"
    local shell_name="$2"

    if [ ! -f "$config_file" ]; then
        echo "⏭️  Skipping $shell_name (config not found: $config_file)"
        return
    fi

    # Remove existing KENL banner block
    if grep -q "# KENL Banner - Start" "$config_file"; then
        echo "Removing existing KENL banner from $shell_name..."
        sed -i '/# KENL Banner - Start/,/# KENL Banner - End/d' "$config_file"
    fi

    if [ -z "$BANNER_CMD" ]; then
        echo "✅ KENL banner removed from $shell_name"
        return
    fi

    # Add new banner block
    cat >> "$config_file" <<EOF

# KENL Banner - Start
# Auto-generated by install-banner.sh - DO NOT EDIT MANUALLY
if [ -t 0 ] && [ -z "\$KENL_BANNER_SHOWN" ]; then
    export KENL_BANNER_SHOWN=1
    $BANNER_CMD
fi
# KENL Banner - End
EOF

    echo "✅ KENL banner installed to $shell_name"
}

# Install to shell configs
echo ""
echo "Installing to shell profiles..."
add_to_shell_config "$HOME/.bashrc" "Bash"
add_to_shell_config "$HOME/.zshrc" "Zsh"

# Offer to add to tmux
if command -v tmux &> /dev/null; then
    read -rp "Install to tmux startup? [y/N]: " tmux_install
    if [[ "$tmux_install" =~ ^[Yy]$ ]]; then
        TMUX_CONF="$HOME/.tmux.conf"

        # Remove existing KENL banner
        if [ -f "$TMUX_CONF" ] && grep -q "# KENL Banner - Start" "$TMUX_CONF"; then
            sed -i '/# KENL Banner - Start/,/# KENL Banner - End/d' "$TMUX_CONF"
        fi

        if [ -n "$BANNER_CMD" ]; then
            mkdir -p "$(dirname "$TMUX_CONF")"
            cat >> "$TMUX_CONF" <<EOF

# KENL Banner - Start
set-hook -g after-new-session 'run-shell "$BANNER_CMD"'
# KENL Banner - End
EOF
            echo "✅ KENL banner installed to tmux"
        fi
    fi
fi

# Create KENL context switcher integration
if [ "$choice" = "6" ]; then
    echo ""
    echo "📝 Context-aware banner selected!"
    echo ""
    echo "To update context when switching KENLs:"
    echo "  mkdir -p ~/.kenl"
    echo "  echo '2' > ~/.kenl/current-context  # For KENL2, etc."
    echo ""
    echo "Or integrate with switch-kenl.sh to auto-update context."
fi

echo ""
echo "🎨 Banner Installation Complete!"
echo ""
echo "To see changes immediately:"
echo "  Bash: source ~/.bashrc"
echo "  Zsh:  source ~/.zshrc"
echo "  Tmux: tmux source-file ~/.tmux.conf"
echo ""
echo "Or open a new terminal session."
echo ""

# Log with ATOM if available
if command -v atom &> /dev/null; then
    atom CONFIG "Installed KENL banner" "Style: $choice"
fi
