#
# Module manifest for module 'KENL'
#
# Generated by: Matthew Ruhnau
#
# Generated on: 2025-11-14
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'KENL.psm1'

# Version number of this module.
ModuleVersion = '1.0.0'

# Supported PSEditions
CompatiblePSEditions = @('Desktop', 'Core')

# ID used to uniquely identify this module
GUID = 'a7f3d5c2-8e9b-4f1a-b6d4-3c7a8f2e1b9d'

# Author of this module
Author = 'Matthew Ruhnau'

# Company or vendor of this module
CompanyName = 'Bazza-DX / KENL Project'

# Copyright statement for this module
Copyright = '(c) 2025 Matthew Ruhnau. All rights reserved.'

# Description of the functionality provided by this module
Description = 'KENL core module for intent-driven gaming and development on Bazzite/Fedora Atomic systems. Provides platform detection, ATOM trail logging, and configuration management for cross-platform (Windows/Linux/macOS) PowerShell environments.'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @(
    'Get-KenlPlatform',
    'Write-AtomTrail',
    'Get-KenlConfig',
    'Set-KenlConfig',
    'New-AtomTag',
    'Get-KenlPath',
    'Test-KenlPrerequisites',
    'Initialize-KenlEnvironment',
    'Get-AtomTrail',
    'Export-AtomTrail',
    'Import-KenlModule'
)

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = @(
    'KenlPlatform',
    'KenlConfigPath',
    'KenlLogsPath',
    'KenlVersion'
)

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @('Bazzite', 'FedoraAtomic', 'Gaming', 'Linux', 'ImmutableOS', 'ATOM', 'SAGE', 'DevOps', 'Configuration', 'AuditTrail', 'Windows', 'CrossPlatform', 'PowerShell')

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/toolate28/kenl/blob/main/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/toolate28/kenl'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = @'
# KENL PowerShell Module v1.0.0

## Initial Release

### Features
- Cross-platform support (Windows, Linux, macOS)
- Platform detection with OS, architecture, and distribution identification
- ATOM trail logging for intent-driven audit trails
- Configuration management (YAML-based)
- ATOM tag generation with auto-incrementing sequence numbers
- Path helpers for KENL directory structure
- Prerequisite checking (git, PowerShell version, disk space)
- Environment initialization for KENL setup
- ATOM trail querying and export capabilities

### Compatibility
- PowerShell 5.1+ (Windows PowerShell)
- PowerShell Core 6.0+ (cross-platform)
- Windows 10/11, macOS 11+, Linux (Fedora, Ubuntu, Arch, Bazzite)

### Documentation
- Complete comment-based help for all functions
- Examples for common workflows
- README with installation and usage instructions

### ATOM Tag
ATOM-MODULE-20251114-001: Released KENL v1.0.0 PowerShell module with cross-platform support
'@

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
HelpInfoURI = 'https://github.com/toolate28/kenl/blob/main/modules/KENL0-system/powershell/README.md'

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}
