#
# Module manifest for module 'KENL.SAIF'
#
# Generated by: KENL Framework
#
# Generated on: 2025-11-25
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'KENL.SAIF.psm1'

# Version number of this module.
ModuleVersion = '1.0.0'

# Supported PSEditions
CompatiblePSEditions = @('Desktop', 'Core')

# ID used to uniquely identify this module
GUID = 'c9f5e7d4-0a1b-5f3c-b8f6-5e9c0h4g3d1f'

# Author of this module
Author = 'toolate28'

# Company or vendor of this module
CompanyName = 'Bazza-DX / KENL Project'

# Copyright statement for this module
Copyright = '(c) 2025 toolate28. All rights reserved.'

# Description of the functionality provided by this module
Description = 'KENL SAIF (System-Aware Intent Flagging) module for guided user journeys. Provides SAIF flag generation, CTFWI handover documents, and next-step guidance to ensure users always know what to do next after each operation.'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.1'

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @('KENL')

# Functions to export from this module
FunctionsToExport = @(
    'New-SAIFFlag',
    'Write-SAIFResult',
    'New-CTFWIHandover',
    'Get-SAIFTrail',
    'Show-SAIFTrail',
    'Initialize-SAIF'
)

# Cmdlets to export from this module
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = @()

# Aliases to export from this module
AliasesToExport = @(
    'saif',
    'saif-show',
    'saif-handover'
)

# Private data to pass to the module specified in RootModule/ModuleToProcess
PrivateData = @{

    PSData = @{

        # Tags applied to this module
        Tags = @('KENL', 'SAIF', 'CTFWI', 'AuditTrail', 'GuidedJourney', 'Intent', 'Handover', 'Windows', 'Linux', 'CrossPlatform')

        # A URL to the license for this module
        LicenseUri = 'https://github.com/toolate28/kenl/blob/main/LICENSE'

        # A URL to the main website for this project
        ProjectUri = 'https://github.com/toolate28/kenl'

        # ReleaseNotes of this module
        ReleaseNotes = @'
# KENL.SAIF PowerShell Module v1.0.0

## Initial Release

### Features
- SAIF flag generation with auto-incrementing counters
- Next-step guidance for all operations
- CTFWI handover document generation
- Color-coded execution results
- Rollback command tracking
- Log path references
- Cross-platform support

### SAIF Action Types
- VALIDATE, PARTITION, INSTALL, CONFIG, OPTIMIZE
- TEST, DEPLOY, BACKUP, RESTORE
- HOOK, CMD, ATOM, HANDOVER, CHECKLIST
- NETWORK, GAMING, MONITORING

### ATOM Tag
ATOM-SAIF-20251125-001: Released KENL.SAIF v1.0.0 module
'@

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
HelpInfoURI = 'https://github.com/toolate28/kenl/blob/main/modules/KENL0-system/powershell/README.md'

}
