#
# Module manifest for module 'KENL.Network'
#
# Generated by: Matthew Ruhnau
#
# Generated on: 2025-11-14
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'KENL.Network.psm1'

# Version number of this module.
ModuleVersion = '1.0.1'

# Supported PSEditions
CompatiblePSEditions = @('Desktop', 'Core')

# ID used to uniquely identify this module
GUID = 'b8e4f6d3-9f0c-4e2b-a7e5-4d8b9g3f2c0e'

# Author of this module
Author = 'Matthew Ruhnau'

# Company or vendor of this module
CompanyName = 'Bazza-DX / KENL Project'

# Copyright statement for this module
Copyright = '(c) 2025 Matthew Ruhnau. All rights reserved.'

# Description of the functionality provided by this module
Description = 'KENL network optimization and testing module for gaming on Bazzite/Fedora Atomic and Windows. Provides latency testing, MTU optimization, TCP window scaling, and network performance monitoring for low-latency gaming. Includes cross-platform support with automatic platform detection.'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @('KENL')

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @(
    'Test-KenlNetwork',
    'Optimize-KenlNetwork',
    'Get-KenlNetworkConfig',
    'Set-KenlMTU',
    'Test-KenlBandwidth',
    'Get-KenlNetworkStatus'
)

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = @(
    'KenlNetworkBaseline',
    'KenlOptimalMTU',
    'KenlTestHosts'
)

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @(
    'Test-Network',
    'Optimize-Network',
    'Test-Latency',
    'Get-MTU',
    'Set-MTU',
    'Get-NetworkStatus'
)

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @('Gaming', 'Network', 'Latency', 'Performance', 'Optimization', 'Bazzite', 'Linux', 'Windows', 'CrossPlatform', 'MTU', 'TCP', 'Bandwidth', 'Proton', 'SteamDeck')

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/toolate28/kenl/blob/main/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/toolate28/kenl'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = @'
# KENL.Network PowerShell Module v1.0.1

## Version 1.0.1 (2025-11-14)

### Bug Fixes
- Fixed latency detection in Test-KenlNetwork (fallback to ping.exe when Test-Connection returns 0ms)
- Improved cross-platform ping command handling (Windows: -n, Linux: -c)

### Enhancements
- Added multi-tier latency detection (Test-Connection with multiple property names, then ping.exe fallback)
- Enhanced error handling for network adapter detection
- Added validation for Test-Connection results (reject 0 or null values)

## Version 1.0.0 (2025-11-12)

### Initial Release

### Features
- Network latency testing with 5 known-good hosts (CDNs, cloud providers)
- Automatic baseline establishment for performance comparison
- MTU optimization with validation (576-9000 bytes)
- TCP window scaling and bandwidth-delay product (BDP) calculation
- Network adapter optimization (RSS, power management)
- Cross-platform support (Windows, Linux via WSL detection)
- ATOM trail integration for all network changes
- Comprehensive error handling and validation
- Color-coded output (EXCELLENT/GOOD/FAIR/POOR thresholds)

### Platform Support
- **Windows**: Full support with NetAdapter cmdlets and netsh
- **Linux**: Basic support via ping, planned full support for Bazzite/Fedora
- **macOS**: Basic support via ping

### Test Hosts
- Best CDN (199.60.103.31) - Expected 25-30ms
- Akamai (23.46.33.251) - Expected 20-40ms
- AWS US-East (18.67.110.92) - Expected 30-50ms
- Google (142.251.221.68) - Expected 20-40ms
- Cloudflare (172.64.36.1) - Expected 15-25ms

### Validation
- Tested on AMD Ryzen 5 5600H + Vega Graphics
- Baseline: 6.2ms average latency (EXCELLENT status)
- Validated with Battlefield 6 gaming workload

### ATOM Tag
ATOM-MODULE-20251114-002: Released KENL.Network v1.0.1 with latency detection fix
'@

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
HelpInfoURI = 'https://github.com/toolate28/kenl/blob/main/modules/KENL0-system/powershell/README.md'

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}
