#
# Module manifest for module 'BattleMedic'
#
# Generated by: Battle Medic Recovery Framework
# Generated on: 2024-11-24
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'BattleMedic.psm1'

# Version number of this module.
ModuleVersion = '2.0.0'

# Supported PSEditions
CompatiblePSEditions = @('Desktop', 'Core')

# ID used to uniquely identify this module
GUID = 'f8d4e3c2-9a6b-4d2e-8c1f-3b7a5e9d2f4c'

# Author of this module
Author = 'Battle Medic Recovery Team'

# Company or vendor of this module
CompanyName = 'Surface Pro 4 EoL Support Initiative'

# Copyright statement for this module
Copyright = '(c) 2024 Battle Medic Recovery. MIT License.'

# Description of the functionality provided by this module
Description = @'
Battle Medic Recovery Suite - Comprehensive Windows recovery and diagnostics framework
specifically optimized for Surface Pro 4 and end-of-life Windows 10 hardware.

This module provides:
- Automated system triage and recovery (P0-P3 priority classification)
- Surface Pro 4 specific hardware issue mitigation
- WOF.SYS BSOD recovery tools
- Thermal management and performance optimization
- Windows Recovery Environment integration
- Comprehensive diagnostic and logging framework
- User-friendly recovery wizards for all skill levels

Designed for both IT professionals managing aging hardware fleets and
end users needing reliable self-service recovery tools.
'@

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module
DotNetFrameworkVersion = '4.5'

# Minimum version of the common language runtime (CLR) required by this module
CLRVersion = '4.0'

# Processor architecture (None, X86, Amd64) required by this module
ProcessorArchitecture = 'None'

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @(
    @{ModuleName = 'CimCmdlets'; ModuleVersion = '1.0.0.0'; GUID = 'fb6cc51d-c096-4b38-b78d-0fed6277096a'},
    @{ModuleName = 'Microsoft.PowerShell.Management'; ModuleVersion = '3.1.0.0'; GUID = 'eefcb906-b326-4e99-9f54-8b4bb6ef3c6d'},
    @{ModuleName = 'Microsoft.PowerShell.Utility'; ModuleVersion = '3.1.0.0'; GUID = '1da87e53-152b-403e-98dc-74d7b4d63d59'}
)

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
TypesToProcess = @('Types\BattleMedic.Types.ps1xml')

# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = @('Formats\BattleMedic.Format.ps1xml')

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
NestedModules = @(
    'Modules\BattleMedic.Diagnostics.psm1',
    'Modules\BattleMedic.Recovery.psm1',
    'Modules\BattleMedic.SP4.psm1',
    'Modules\BattleMedic.WinRE.psm1',
    'Modules\BattleMedic.Logging.psm1'
)

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @(
    # Core Diagnostics
    'Get-SystemHealthReport',
    'Get-HardwareStatus',
    'Get-SP4Status',
    'Test-SystemPriority',
    'Get-BattleMedicDiagnostic',

    # Recovery Operations
    'Start-BattleMedicRecovery',
    'Repair-WOFDriver',
    'Repair-SystemFiles',
    'Start-EmergencyCleanup',
    'Reset-WindowsUpdate',

    # SP4 Specific
    'Repair-SP4ScreenFlicker',
    'Repair-SP4TypeCover',
    'Repair-SP4Sleep',
    'Reset-SP4GPUDriver',
    'Start-SP4ThermalMitigation',

    # WinRE Integration
    'Install-BattleMedicToWinRE',
    'Start-WinRERecovery',
    'Get-WinREStatus',

    # Logging and Reporting
    'Get-BattleMedicLog',
    'Export-BattleMedicReport',
    'New-RecoveryCheckpoint',
    'Get-RecoveryHistory',

    # User Interface
    'Show-RecoveryMenu',
    'Start-GuidedRecovery',
    'Start-AutomatedRecovery'
)

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = @(
    'BattleMedicVersion',
    'BattleMedicConfig'
)

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @(
    'bmr',      # Start-BattleMedicRecovery
    'bmdiag',   # Get-BattleMedicDiagnostic
    'bmlog',    # Get-BattleMedicLog
    'sp4fix',   # Start-SP4Recovery
    'woffix'    # Repair-WOFDriver
)

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
FileList = @(
    'BattleMedic.psd1',
    'BattleMedic.psm1',
    'Modules\BattleMedic.Diagnostics.psm1',
    'Modules\BattleMedic.Recovery.psm1',
    'Modules\BattleMedic.SP4.psm1',
    'Modules\BattleMedic.WinRE.psm1',
    'Modules\BattleMedic.Logging.psm1',
    'Types\BattleMedic.Types.ps1xml',
    'Formats\BattleMedic.Format.ps1xml',
    'Config\DefaultConfig.json',
    'Resources\RecoveryMenu.xaml',
    'Resources\Messages.psd1',
    'Tests\BattleMedic.Tests.ps1'
)

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @(
            'Recovery',
            'Diagnostics',
            'Surface',
            'SurfacePro4',
            'SP4',
            'Windows10',
            'WindowsRecovery',
            'WinRE',
            'SystemRepair',
            'BSOD',
            'WOF',
            'EndOfLife',
            'EoL',
            'Maintenance',
            'ThermalManagement',
            'PSEdition_Desktop',
            'PSEdition_Core',
            'Windows'
        )

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/battlemedic/BattleMedic/blob/main/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/battlemedic/BattleMedic'

        # A URL to an icon representing this module.
        IconUri = 'https://github.com/battlemedic/BattleMedic/blob/main/Resources/icon.png'

        # ReleaseNotes of this module
        ReleaseNotes = @'
## Version 2.0.0
- Complete PowerShell module rewrite
- Added comprehensive SP4 hardware support
- Integrated WinRE recovery tools
- New GUI recovery menu
- Enhanced logging and diagnostics
- Added automated recovery modes
- Improved error handling and rollback
- Added checkpoint/restore functionality
'@

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
HelpInfoURI = 'https://github.com/battlemedic/BattleMedic/wiki'

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}
